# Generated by Django 3.2.23 on 2023-11-18 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=999)),
                ('nickname', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^@.+$', 'Nickname must start with "@"')])),
            ],
        ),
    ]
